version: '3'

services:
    webserver:
        image: tjozsa/seleniumsink
        build: .
        ports:
            - 9999:80
    postgres:
    image: "postgres:11"
    container_name: "realworld_postgres"
    ports:
      - "54320:5432"
    volumes:
      - ./.docker/data:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=userpassword
    networks:
      - drash-app-network

networks:
  drash-app-network:
    driver: bridge
