# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginok():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login1(self):
    self.driver.get("http://localhost:1667/")
    self.driver.set_window_size(1017, 909)
    self.driver.find_element(By.LINK_TEXT, "Sign in").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset/input").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset/input").send_keys("kincsesl@freemail.hu")
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset[2]/input").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset[2]/input").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset[2]/input").send_keys("Testuser123")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
  
  def test_login2(self):
    self.driver.get("http://localhost:1667/")
    self.driver.set_window_size(1017, 909)
    self.driver.find_element(By.LINK_TEXT, "Sign in").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").send_keys("user@user.com")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").send_keys("Testuser123")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
  
